services:
  - type: web
    name: wura-grand-server
    env: node
    region: oregon
    plan: starter
    branch: main
    repo: https://github.com/Iconvibes/Wura
    buildCommand: "npm install && npm run setup && npm run build"
    startCommand: "npm start"
    healthCheckPath: "/api/rooms"
    autoDeploy: true
