// Self-hosted photography (Unsplash License — free for commercial use).
// Files live in client/public/images/ so Vite serves them at /images/…
//
// Shared between the React client and the Express prerender: the prerender
// uses the same registry to emit per-room og:image / twitter:image URLs, so
// social crawlers and the SPA always agree on the photo for a room.
//
// Every one of the 50 seeded rooms has its OWN photography — 100 distinct
// photos (two per room), no photo is reused anywhere. Cards, detail galleries
// and social previews are therefore unique per room.

export const HERO_IMAGE = '/images/hero.jpg';

// Responsive width variants generated by `npm run generate:images` into
// <dir>/resp/<base>-<w>.jpg for every self-hosted image (room pool, page
// banners, hero). Must match WIDTHS in scripts/generate-image-variants.mjs.
export const IMG_RESP_WIDTHS = [480, 800, 1200];

/** srcset string for a self-hosted photo, or null when no variants exist
 * (admin uploads and non-image / non-/images paths). Sizes are chosen per
 * component with a `sizes` attribute; omitting srcset keeps the plain `src`
 * fallback for anything outside the generated pool. `fmt` picks the codec:
 * 'jpg' (default) | 'webp' | 'avif' — the generator emits all three per width
 * and <picture> serves them in that order. */
export function imgSrcset(src, fmt = 'jpg') {
  if (typeof src !== 'string' || !src.startsWith('/images/') || src.startsWith('/images/uploads/')) return null;
  if (!/\.jpe?g$/i.test(src)) return null;
  const m = src.match(/^(.*\/)([^/]+)\.jpe?g$/i);
  if (!m) return null;
  const [, dir, base] = m;
  const ext = fmt === 'avif' ? 'avif' : fmt === 'webp' ? 'webp' : 'jpg';
  return IMG_RESP_WIDTHS.map((w) => `${dir}resp/${base}-${w}.${ext} ${w}w`).join(', ');
}

// Fallback pool keyed by room type (used only if a room has no name entry,
// e.g. a room the admin adds later).
export const ROOM_PHOTOS = {
  Standard: '/images/rooms/standard.jpg',
  Deluxe: '/images/rooms/deluxe.jpg',
  Suite: '/images/rooms/suite.jpg',
  Penthouse: '/images/rooms/penthouse.jpg',
};

// Per-room pools — each seeded room gets its own photography, keyed by the
// stable seeded NAME (ObjectIds change on every reseed, names do not).
// The first entry is the card hero; the rest power the detail gallery.
export const ROOM_PHOTOS_BY_NAME = {
  'Classic Queen': ['/images/rooms/classic-queen-1.jpg', '/images/rooms/classic-queen-2.jpg'],
  'Classic Twin': ['/images/rooms/classic-twin-1.jpg', '/images/rooms/classic-twin-2.jpg'],
  'Classic Queen Garden': ['/images/rooms/classic-queen-garden-1.jpg', '/images/rooms/classic-queen-garden-2.jpg'],
  'Classic Twin Garden': ['/images/rooms/classic-twin-garden-1.jpg', '/images/rooms/classic-twin-garden-2.jpg'],
  'Accessible King': ['/images/rooms/accessible-king-1.jpg', '/images/rooms/accessible-king-2.jpg'],
  'Family King': ['/images/rooms/family-king-1.jpg', '/images/rooms/family-king-2.jpg'],
  'Classic Queen Courtyard': ['/images/rooms/classic-queen-courtyard-1.jpg', '/images/rooms/classic-queen-courtyard-2.jpg'],
  'Classic Queen 2nd Floor': ['/images/rooms/classic-queen-2nd-floor-1.jpg', '/images/rooms/classic-queen-2nd-floor-2.jpg'],
  'Classic Twin 3rd Floor': ['/images/rooms/classic-twin-3rd-floor-1.jpg', '/images/rooms/classic-twin-3rd-floor-2.jpg'],
  'Classic Twin 4th Floor': ['/images/rooms/classic-twin-4th-floor-1.jpg', '/images/rooms/classic-twin-4th-floor-2.jpg'],
  'Family King Garden': ['/images/rooms/family-king-garden-1.jpg', '/images/rooms/family-king-garden-2.jpg'],
  'Classic Queen 5th Floor': ['/images/rooms/classic-queen-5th-floor-1.jpg', '/images/rooms/classic-queen-5th-floor-2.jpg'],
  'Deluxe King': ['/images/rooms/deluxe-king-1.jpg', '/images/rooms/deluxe-king-2.jpg'],
  'Deluxe Garden': ['/images/rooms/deluxe-garden-1.jpg', '/images/rooms/deluxe-garden-2.jpg'],
  'Deluxe King Skyline': ['/images/rooms/deluxe-king-skyline-1.jpg', '/images/rooms/deluxe-king-skyline-2.jpg'],
  'Deluxe Terrace': ['/images/rooms/deluxe-terrace-1.jpg', '/images/rooms/deluxe-terrace-2.jpg'],
  'Studio Loft': ['/images/rooms/studio-loft-1.jpg', '/images/rooms/studio-loft-2.jpg'],
  'Garden Cottage': ['/images/rooms/garden-cottage-1.jpg', '/images/rooms/garden-cottage-2.jpg'],
  'Deluxe King Corner': ['/images/rooms/deluxe-king-corner-1.jpg', '/images/rooms/deluxe-king-corner-2.jpg'],
  'Deluxe King 12th Floor': ['/images/rooms/deluxe-king-12th-floor-1.jpg', '/images/rooms/deluxe-king-12th-floor-2.jpg'],
  'Deluxe Garden 2nd Floor': ['/images/rooms/deluxe-garden-2nd-floor-1.jpg', '/images/rooms/deluxe-garden-2nd-floor-2.jpg'],
  'Deluxe Terrace Skyline': ['/images/rooms/deluxe-terrace-skyline-1.jpg', '/images/rooms/deluxe-terrace-skyline-2.jpg'],
  'Junior Loft': ['/images/rooms/junior-loft-1.jpg', '/images/rooms/junior-loft-2.jpg'],
  'Deluxe King 15th Floor': ['/images/rooms/deluxe-king-15th-floor-1.jpg', '/images/rooms/deluxe-king-15th-floor-2.jpg'],
  'Junior Suite': ['/images/rooms/junior-suite-1.jpg', '/images/rooms/junior-suite-2.jpg'],
  'Deluxe Suite': ['/images/rooms/deluxe-suite-1.jpg', '/images/rooms/deluxe-suite-2.jpg'],
  'Executive Suite': ['/images/rooms/executive-suite-1.jpg', '/images/rooms/executive-suite-2.jpg'],
  'Family Suite': ['/images/rooms/family-suite-1.jpg', '/images/rooms/family-suite-2.jpg'],
  'Skyline Suite': ['/images/rooms/skyline-suite-1.jpg', '/images/rooms/skyline-suite-2.jpg'],
  'Ambassador Suite': ['/images/rooms/ambassador-suite-1.jpg', '/images/rooms/ambassador-suite-2.jpg'],
  'Heritage Suite': ['/images/rooms/heritage-suite-1.jpg', '/images/rooms/heritage-suite-2.jpg'],
  'Junior Suite City View': ['/images/rooms/junior-suite-city-view-1.jpg', '/images/rooms/junior-suite-city-view-2.jpg'],
  'Deluxe Suite Skyline': ['/images/rooms/deluxe-suite-skyline-1.jpg', '/images/rooms/deluxe-suite-skyline-2.jpg'],
  'Executive Suite Corner': ['/images/rooms/executive-suite-corner-1.jpg', '/images/rooms/executive-suite-corner-2.jpg'],
  'Family Suite Garden': ['/images/rooms/family-suite-garden-1.jpg', '/images/rooms/family-suite-garden-2.jpg'],
  'Ambassador Suite Skyline': ['/images/rooms/ambassador-suite-skyline-1.jpg', '/images/rooms/ambassador-suite-skyline-2.jpg'],
  'Heritage Garden Suite': ['/images/rooms/heritage-garden-suite-1.jpg', '/images/rooms/heritage-garden-suite-2.jpg'],
  'Junior Suite 7th Floor': ['/images/rooms/junior-suite-7th-floor-1.jpg', '/images/rooms/junior-suite-7th-floor-2.jpg'],
  'Presidential': ['/images/rooms/presidential-1.jpg', '/images/rooms/presidential-2.jpg'],
  'Skyline Penthouse': ['/images/rooms/skyline-penthouse-1.jpg', '/images/rooms/skyline-penthouse-2.jpg'],
  'Royal Villa': ['/images/rooms/royal-villa-1.jpg', '/images/rooms/royal-villa-2.jpg'],
  'Garden Villa': ['/images/rooms/garden-villa-1.jpg', '/images/rooms/garden-villa-2.jpg'],
  'Penthouse Studio': ['/images/rooms/penthouse-studio-1.jpg', '/images/rooms/penthouse-studio-2.jpg'],
  'Skyline Penthouse East': ['/images/rooms/skyline-penthouse-east-1.jpg', '/images/rooms/skyline-penthouse-east-2.jpg'],
  'Royal Villa Garden': ['/images/rooms/royal-villa-garden-1.jpg', '/images/rooms/royal-villa-garden-2.jpg'],
  'Observatory Penthouse': ['/images/rooms/observatory-penthouse-1.jpg', '/images/rooms/observatory-penthouse-2.jpg'],
  'Penthouse Studio City': ['/images/rooms/penthouse-studio-city-1.jpg', '/images/rooms/penthouse-studio-city-2.jpg'],
  'Presidential Reserve': ['/images/rooms/presidential-reserve-1.jpg', '/images/rooms/presidential-reserve-2.jpg'],
  'Penthouse Suite 20th Floor': ['/images/rooms/penthouse-suite-20th-floor-1.jpg', '/images/rooms/penthouse-suite-20th-floor-2.jpg'],
  'Skyline Penthouse West': ['/images/rooms/skyline-penthouse-west-1.jpg', '/images/rooms/skyline-penthouse-west-2.jpg'],
};

/** Card photo for a room: admin-chosen photos first, then the room's own
 * seeded pool, then the type fallback. */
export function roomPhoto(room) {
  if (room && Array.isArray(room.photos) && room.photos.length) return room.photos[0];
  const pool = room && ROOM_PHOTOS_BY_NAME[room.name];
  if (pool && pool.length) return pool[0];
  return ROOM_PHOTOS[(room && room.type) || 'Standard'] || ROOM_PHOTOS.Standard;
}

/** Full gallery for a room's detail page: admin-chosen photos first, then the
 * per-room pool, then the type fallback. */
export function roomPhotos(room) {
  if (room && Array.isArray(room.photos) && room.photos.length) return room.photos;
  const pool = room && ROOM_PHOTOS_BY_NAME[room.name];
  if (pool && pool.length) return pool;
  const type = (room && room.type) || 'Standard';
  return [ROOM_PHOTOS[type] || ROOM_PHOTOS.Standard, HERO_IMAGE];
}

/** URL-safe slug for a room name — shared by the social-card generator, the
 * SPA and the prerender so filenames and og:image URLs always agree. */
export function roomSlug(name) {
  return String(name || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/** Branded social-card (og:image) path for a room's page. Only seeded rooms
 * have a generated card; admin-created rooms fall back to their photo (their
 * slug has no card on disk, so the branded URL would 404). */
export function roomCardImage(room) {
  if (room && ROOM_PHOTOS_BY_NAME[room.name]) return `/social/rooms/${roomSlug(room.name)}.png`;
  return roomPhoto(room);
}
